# Generated by Django 2.2.5 on 2019-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190929_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
