# Generated by Django 2.2.5 on 2019-09-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
