# Generated by Django 2.2.5 on 2019-10-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191002_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('D', '$'), ('T', 'TL')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
