# Generated by Django 2.2.5 on 2019-10-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('KE', 'Kadın Elbisesi'), ('EE', 'Erker Elbisesi')], max_length=2),
        ),
    ]
